url: https://ingascouter.github.io
timezone: Europe/Helsinki
lang: sv
title: Ingå Scouter
description: En scoutkår i Ingå, Finland

defaults:
  -
    scope:
      path: "" # all files in the project
      type: "pages"
    values:
      layout: "default"
      banner: "/assets/banners/banner.png"
      date: 01-01-1970
      toc: true

plugins:
  # - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-toc

feed:
  posts_limit: 20
  categories:
    - news